# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfa50b465be07072f46ee843a2f49bfecced08924f1c0b08480e12dc80aef9d319b68da96d17a437241748597c655d874b0aa0f9bf4f83a527b2346dfb92c704

test:
  secret_key_base: ebfe9140db33cd73c62fefb7703e26fa81679b88d63b4470791fbed9ea617ae8e8baf74ec107efb38f6454ec19f7788aaf0d5a1566843b241de1e8839e7c4656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4fd18df5b396523e2f607bcf500f668d95dc3e0f31a5b093b48fbf37e0ad3381338028234503b32bf7cdf3620cf301b2b12997e5fcd7b8491db2f8d995753505
